### ISSUE TITLE
help!  npm run build  is error.

### ISSUE THREAD

**Issue by zhanghao001** [apache/incubator-skywalking-ui#192]
when I run npm run build,get a error:

> skywalking-ui@5.0.0-RC build /Users/zh/incubator-skywalking-ui
> cross-env DISABLE_ESLINT=true roadhog build

Warning: DISABLE_ESLINT is deprecated, use ESLINT=none instead has been deprecated.
TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at WriteStream.Socket.write (net.js:666:11)
    at nodeDeprecate (/Users/zh/incubator-skywalking-ui/node_modules/deprecate/index.js:22:22)
    at deprecate (/Users/zh/incubator-skywalking-ui/node_modules/deprecate/index.js:11:3)
    at Object.<anonymous> (/Users/zh/incubator-skywalking-ui/node_modules/af-webpack/lib/getConfig.js:81:26)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zh/incubator-skywalking-ui/node_modules/af-webpack/getConfig.js:1:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
[graceful-process#20410] exit with code:1

npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/zh/.nvm/versions/node/v6.14.4/bin/node" "/Users/zh/.nvm/versions/node/v6.14.4/bin/npm" "run" "build"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! skywalking-ui@5.0.0-RC build: `cross-env DISABLE_ESLINT=true roadhog build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skywalking-ui@5.0.0-RC build script 'cross-env DISABLE_ESLINT=true roadhog build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the skywalking-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env DISABLE_ESLINT=true roadhog build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs skywalking-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls skywalking-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zh/incubator-skywalking-ui/npm-debug.log

My node is v6.14.4, npm is 3.10.10. How can I do?

**Comment by wu-sheng** [comment]
I don't think it is caused by codes. Our CI is still working, and everything looks like good. 

If you have network issue(sometime even need proxy), try to use taobao proxy instead of official one.
